Data tile refactor
grupadotnet/Aqua-Sharp-Frontend pull request #21
Opened 2023-04-21 21:03 UTC by ThePanToster

Teraz można tworzyć 3 rodzaje tajli:
- Tile (dowolne children)
![image](https://user-images.githubusercontent.com/73584389/233733944-e2713a6d-184e-4cd7-9c7a-a1891005ccfc.png)
- DataTile
![image](https://user-images.githubusercontent.com/73584389/233734023-294fd253-103d-465c-8ac1-834028a2a2b7.png)
- LightControlTile
![image](https://user-images.githubusercontent.com/73584389/233734094-c10969a6-1813-4297-82c3-1f9c935b601e.png)

Jak coś trzeba zmienić to mówić

2023-04-21 21:13 UTC, ThePanToster commented
Zmieniłem nazwę komponentu "Tile" na "Card", bo zauważyłem, że Patryk już robi taki komponent

2023-04-22 07:09 UTC, SzczepanWikar requested changes

2023-04-22 07:09 UTC, SzczepanWikar commented on src/components/card/Card.tsx
> +  theme:
Theme do osobnego typu.

2023-04-22 07:09 UTC, SzczepanWikar commented on src/components/card/Card.tsx
> +const Crd = ({ children, theme }: Props) => (
Card, nie Crd

2023-04-22 07:18 UTC, ThePanToster commented on src/components/card/Card.tsx
> +const Crd = ({ children, theme }: Props) => (
Zmienione na DataCard, Card jest zarezerwowane dla react bootstrapa

2023-04-22 07:50 UTC, ThePanToster commented on src/components/card/Card.tsx
> +  theme:
🤙🤙🤙 Zrobione

2023-04-22 08:33 UTC, SzczepanWikar approved these changes

2023-04-22 08:33 UTC, merged