Edit view added
grupadotnet/Aqua-Sharp-Frontend pull request #22
Opened 2023-04-22 12:24 UTC by ThePanToster

![image](https://user-images.githubusercontent.com/73584389/233784550-58ecc24e-fe7c-4eb2-a509-38c2685e0575.png)
Responsywność ogarnięta w miarę, walidacji formularza nie robiłem

2023-04-22 12:49 UTC, ThePanToster commented
![image](https://user-images.githubusercontent.com/73584389/233785619-98ae86c8-7f3f-4197-8096-cfa6235b2e9e.png)
![image](https://user-images.githubusercontent.com/73584389/233785630-a3d712e0-9699-41d5-a16e-3ad8299e82de.png)
![image](https://user-images.githubusercontent.com/73584389/233785640-66777e02-e1dd-4cb3-b6b2-ac514d80d6f6.png)

2023-04-22 12:53 UTC, ThePanToster commented
Naprawiłem pole "Częstotliwość" na mobilce
![image](https://user-images.githubusercontent.com/73584389/233785758-6b853310-d7c3-473a-ae3c-4a394a70ee28.png)

2023-04-24 20:14 UTC, JN0122 requested changes
Dodaj tłumaczenia i leci merge :)

2023-04-24 20:14 UTC, JN0122 commented on src/pages/edit/index.tsx
> +      <h3 className="mb-4">Konfigurowanie akwarium</h3>
Tak samo jak w drugim PR - tłumaczenia

2023-04-25 16:58 UTC, JN0122 approved these changes

2023-04-25 16:58 UTC, merged