Added settings view
grupadotnet/Aqua-Sharp-Frontend pull request #23
Opened 2023-04-22 15:21 UTC by ThePanToster

![image](https://user-images.githubusercontent.com/73584389/233792921-5686208f-b9ec-4c5f-be7f-ce2a229c460d.png)
![image](https://user-images.githubusercontent.com/73584389/233792950-bd35ea1f-7187-49f8-90ea-8cbe4ab61d1f.png)
![image](https://user-images.githubusercontent.com/73584389/233792962-d3dcf323-bbae-4fb6-8a5b-6175c1f66903.png)

2023-04-24 20:12 UTC, JN0122 requested changes
Wszystko super tylko trzeba jedną wprowadzić :)

2023-04-24 20:12 UTC, JN0122 commented on src/pages/settings/index.tsx
> +          <Tile title="Zmiana hasła">
Tłumaczenie

2023-04-24 20:12 UTC, JN0122 commented on src/pages/settings/index.tsx
> +      <h3 className="mb-4">Profil</h3>
Nie wpisujemy na sztywno tekstu, lepiej skorzystać z tłumaczeń. Zerknij sobie do pliku _src/pages/working:37_, tutaj masz przykładowe użycie. Wszystkie tłumaczenia znajduja się _public/assets/locales_.

2023-04-24 20:12 UTC, JN0122 commented on src/pages/settings/index.tsx
> +                  <PasswordInput placeholder="Stare hasło" />
Tłumaczenie

2023-04-24 20:12 UTC, JN0122 commented on src/pages/settings/index.tsx
> +                  <PasswordInput placeholder="Nowe hasło" />
Tłumaczenie

2023-04-24 20:12 UTC, JN0122 commented on src/pages/settings/index.tsx
> +                  <PasswordInput placeholder="Powtórz hasło" />
Tłumaczenie

2023-04-24 20:12 UTC, JN0122 commented on src/pages/settings/index.tsx
> +                  Zmień hasło
Tłumaczenie

2023-04-24 20:12 UTC, JN0122 commented on src/pages/settings/index.tsx
> +          <Tile title="Zmiana pytania kontrolnego">
Tłumaczenie

2023-04-24 20:12 UTC, JN0122 commented on src/pages/settings/index.tsx
> +                  <PasswordInput placeholder="Hasło" />
Tłumaczenie

2023-04-24 20:12 UTC, JN0122 commented on src/pages/settings/index.tsx
> +                  <Input placeholder="Pytanie" />
Tłumaczenie

2023-04-24 20:12 UTC, JN0122 commented on src/pages/settings/index.tsx
> +                  <Input placeholder="Odpowiedź" />
Tłumaczenie

2023-04-24 20:12 UTC, JN0122 commented on src/pages/settings/index.tsx
> +                  Zmień pytanie
Tłumaczenie

2023-04-24 20:12 UTC, JN0122 commented on src/pages/settings/index.tsx
> +          <Tile title="Język">
Tłumaczenie

2023-04-25 00:20 UTC, ThePanToster commented
Łoł, spokojnie, za pierwszym razem dotarło 😉

2023-04-25 13:56 UTC, ThePanToster commented
![image](https://user-images.githubusercontent.com/73584389/234299527-36a09dd1-52e9-48f6-a35b-19088b0918dc.png)

2023-04-25 15:01 UTC, JN0122 approved these changes

2023-04-25 15:01 UTC, merged