Header
grupadotnet/Aqua-Sharp-Frontend pull request #28
Opened 2023-05-04 07:38 UTC by wiktorrudzki

![image](https://user-images.githubusercontent.com/95183973/236140037-a7d09882-594f-4072-b9c0-bba09aeddcfc.png)

2023-05-04 10:27 UTC, JN0122 requested changes

2023-05-04 10:27 UTC, JN0122 commented on src/App.tsx
Wszystko spoko tylko czy można by wyciągnąć ten komponent DashboardLayout nad Route, żeby się nie powtarzać?

2023-05-06 09:12 UTC, wiktorrudzki commented on src/App.tsx
niestety się nie da, w komponencie <Routes> mogą być tylko zagnieżdżone komponenty <Route />

2023-05-07 18:21 UTC, JN0122 approved these changes

2023-05-07 18:21 UTC, merged