label refactor
grupadotnet/Aqua-Sharp-Frontend pull request #30
Opened 2023-05-06 12:07 UTC by wiktorrudzki

![image](https://user-images.githubusercontent.com/95183973/236623060-cc26e49b-9dbe-4c5d-97ef-1f77cba95d4f.png)

2023-05-07 19:20 UTC, JN0122 requested changes

2023-05-07 19:20 UTC, JN0122 commented on src/components/input/InputGroup.tsx
> +    <Form.Label className="mt-4 mb-0">
Jakbyś mógł zmienić odstępy, bo jest trochę asymetrycznie to wygląda

2023-05-07 19:20 UTC, JN0122 commented on src/pages/edit/index.tsx
> +              <Form.Label className="mt-4 mb-0">
Można by je wydzielić do osobnego komponentu, żeby w 3 miejscach nie pisać tego samego

2023-05-08 16:19 UTC, wiktorrudzki commented
bardzo proszę o dokładne przejrzenie, bo sporo rzeczy się zmieniło

2023-05-11 18:40 UTC, JN0122 approved these changes

2023-05-11 18:40 UTC, merged