Button component & tests
grupadotnet/Aqua-Sharp-Frontend pull request #4
Opened 2023-01-19 18:55 UTC by ThePanToster

![image](https://user-images.githubusercontent.com/73584389/213532817-5ba82e4f-71d3-47d9-a9fe-62381a2741cb.png)
![image](https://user-images.githubusercontent.com/73584389/213532952-5cc44076-8f9b-440e-b6e5-efb2e381b17a.png)
![image](https://user-images.githubusercontent.com/73584389/213534071-9df4d64c-2dbe-4c3a-a2a3-1d05a4fc0cb9.png)
Wiem że w testach się makabra dzieje, ale w dokumentacji Reacta każą używać act() przy testach, a domyślnie wywala warningi i żeby je wyłączyć trzeba globala zmienić, a TypeScript tego nie lubi no i wyszło to co wyszło. Ale działa!

2023-01-20 08:10 UTC, SzczepanWikar commented on src/components/button/index.tsx
> +function Button(props: IButton) {
Zamiast function używaj export const

2023-01-20 08:10 UTC, SzczepanWikar commented on src/components/button/index.tsx
> +  type: 'OK' | 'Cancel' | 'Action',
Teraz o tym pomyślałem, ale niech type będzie opcjonalne. A gdy nie będzie podane, niech po prostu będzie styl dla action.

2023-01-20 08:10 UTC, SzczepanWikar commented on src/components/button/index.tsx
> +        case 'OK':
lepiej byłoby aby był tylko jeden return, a manewrowanie byłoby tylko na poziomie listy klas.

2023-01-21 01:42 UTC, ThePanToster commented
Podgląd wszystkich kombinacji:
![image](https://user-images.githubusercontent.com/73584389/213832709-48e3c1f1-c22e-4b67-9304-5196eea55e5a.png)
> Zamiast function używaj export const

Zrobione
> Teraz o tym pomyślałem, ale niech type będzie opcjonalne.

Zrobione
> a manewrowanie byłoby tylko na poziomie listy klas

Nie rozumiem przekazu, ale zrobiłem coś takiego:

![image](https://user-images.githubusercontent.com/73584389/213834582-23f1cc5d-421f-4651-ada9-9f34768e2e26.png)

2023-01-21 17:02 UTC, wiktorrudzki requested changes
Moim zdaniem spoko komponent, proponuje dodać puste linie na koniec plików i zastanowić się nad jedną rzeczą.
@SzczepanWikar  @ThePanToster co zrobimy w sytuacji, gdy nasz button ma zajmować 100% dostępnej szerokości?
![image](https://user-images.githubusercontent.com/95183973/213878180-d72a9a90-54cf-46c5-af35-36d9bc8260ce.png)
Ja myślałem, żeby można ewentualnie dodać opcjonalnego propsa, którym będziemy definiować jak długi będzie przycisk, a wy co myślicie?

2023-01-21 17:02 UTC, wiktorrudzki commented on src/components/button/index.tsx
> +export const Button = (props: IButton) => {
tutaj dobrze zrobiłeś z exportem defaultowyn. Funkcja strzałkowa może zostać, ale eksportuj komponent poniżej jako default. Komponenty globalne będziemy zawsze eksportować jak default

2023-01-21 19:48 UTC, ThePanToster commented
> Ja myślałem, żeby można ewentualnie dodać opcjonalnego propsa, którym będziemy definiować jak długi będzie przycisk

Też nad tym myślałem, bo się zastanawiałem czy jak się w React'cie stronę z componentów buduje, to czy np. rozciąganie flex'em na nich zadziała

2023-01-21 20:10 UTC, ThePanToster commented on src/components/button/index.tsx
> +export const Button = (props: IButton) => {
> eksportuj komponent poniżej jako default

Zrobione

2023-01-22 16:12 UTC, wiktorrudzki commented
> > Ja myślałem, żeby można ewentualnie dodać opcjonalnego propsa, którym będziemy definiować jak długi będzie przycisk
> 
> Też nad tym myślałem, bo się zastanawiałem czy jak się w React'cie stronę z componentów buduje, to czy np. rozciąganie flex'em na nich zadziała

@SzczepanWikar co myślisz?

2023-01-22 16:13 UTC, wiktorrudzki requested changes

2023-01-22 16:13 UTC, wiktorrudzki commented on src/components/button/index.tsx
> +export const Button = (props: IButton) => {
to jeszcze usuń export z linijki 8 bo teraz jest on nam już niepotrzebny :D

2023-01-22 16:16 UTC, SzczepanWikar commented
> 

Ja myślę, że jeżeli dałoby się to zrobić css'em w kontenerze, to tak będzie lepiej. @ThePanToster Sprawdź, czy się da. Powinno się dać. Jeżeli tak to zostawiłbym to tak, jeżeli nie, to zrób tego propsa.

2023-01-23 10:33 UTC, ThePanToster commented on src/components/button/index.tsx
> +export const Button = (props: IButton) => {
👍

2023-01-23 10:53 UTC, ThePanToster commented
![image](https://user-images.githubusercontent.com/73584389/214022182-69a8c14d-fc2f-44b1-b201-7e2e0eafe432.png)
![image](https://user-images.githubusercontent.com/73584389/214022265-c61c435f-8a43-4394-8712-85c55a56e11b.png)
Przetestowałem, da się stylami kontenera zmieniać width buttona

2023-01-24 11:54 UTC, wiktorrudzki approved these changes

2023-01-24 13:38 UTC, merged